### ISSUE TITLE
关于操作逻辑

### ISSUE THREAD

**Issue by youranreus** [trisolaris233/FancyBox#1]
作者你好!
关于插件的解析过滤，我觉得与其从整个页面遍历img标签倒不如从指定div遍历img标签。这样我觉得更方便一些！
（一个个设置好麻烦QAQ）

**Comment by trisolaris233** [comment]
嗯！ 似乎的确是个问题呢！ 
以前我只为了能用就行没考虑太多要不你帮我改改(太不负责了

**Comment by youranreus** [comment]
其实只要把plugin.php的第101行的 `$("img").each` 改成 `$("#post img").each` 这样子就好啦(ﾟ∀ﾟ)
